version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=production
    networks:
      - my-network

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api
    networks:
      - my-network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
